version: '3'

services:
  Ganache:
    build: ./ManualFABToken
    environment:
      - ID=ganache
    ports:
      - 8777:8777
  ManualFABToken:
    build: ./ManualFABToken
    environment:
      - ID=contract
    ports:
      - 8545:8545
